In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("50_startups.csv")

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [6]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace=True)

In [7]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[3])],remainder="passthrough")
x=ct.fit_transform(x)

In [9]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [10]:
x.shape

(50, 6)

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)

In [40]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [42]:
cat=Sequential()

In [43]:
cat.add(Dense(4,kernel_initializer="random_uniform",activation="relu"))

In [44]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

In [45]:
cat.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [46]:
cat.compile("adam","mean_squared_error",metrics=["MSE"])

In [47]:
cat.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
40/40 [==============================] - 0s 7ms/sample - loss: 13933870694.4000 - mean_squared_error: 13933871104.0000
Epoch 2/10
40/40 [==============================] - 0s 224us/sample - loss: 13933870489.6000 - mean_squared_error: 13933871104.0000
Epoch 3/10
40/40 [==============================] - 0s 274us/sample - loss: 13933869465.6000 - mean_squared_error: 13933869056.0000
Epoch 4/10
40/40 [==============================] - 0s 299us/sample - loss: 13933869465.6000 - mean_squared_error: 13933869056.0000
Epoch 5/10
40/40 [==============================] - 0s 399us/sample - loss: 13933868032.0000 - mean_squared_error: 13933868032.0000
Epoch 6/10
40/40 [==============================] - 0s 299us/sample - loss: 13933867417.6000 - mean_squared_error: 13933868032.0000
Epoch 7/10
40/40 [==============================] - 0s 175us/sample - loss: 13933867827.2000 - mean_squared_error: 13933868032.0000
Epoch 8/10
40/40 [==============================] - 0s 299us/sample - loss: 13

In [48]:
ypred=cat.predict(x_test)

In [49]:
ypred

array([[0.02610768],
       [0.02667668],
       [0.03017728],
       [0.02554109],
       [0.02832606],
       [0.02652584],
       [0.02596935],
       [0.02695497],
       [0.02635674],
       [0.02634586]], dtype=float32)

In [50]:
y_test

array([ 96712.8 ,  90708.19, 191792.06,  81229.06, 152211.77, 126992.93,
        96479.51, 134307.35, 101004.64, 108552.04])

In [51]:
dataset.head(1)

R&D Spend  Administration  Marketing Spend     State     Profit
0   165349.2        136897.8         471784.1  New York  192261.83

In [52]:
cat.predict(sc.transform(ct.transform([[165349.2,136897.8,471784.1,"New York"]])))

array([[0.03033368]], dtype=float32)

In [54]:
cat.predict_classes(sc.transform(ct.transform([[165349.2,136897.8,471784.1,"New York"]])))

array([[0]])