In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset=pd.read_csv("petrol_consumption.csv")

In [3]:
dataset.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [4]:
dataset.isnull().any()

Petrol_tax                      False
Average_income                  False
Paved_Highways                  False
Population_Driver_licence(%)    False
Petrol_Consumption              False
dtype: bool

In [5]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1000)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [9]:
cat=Sequential()

In [10]:
cat.add(Dense(4,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [11]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

In [12]:
cat.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [13]:
cat.compile("adam","mean_squared_error",metrics=["MSE"])

In [14]:
cat.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
38/38 [==============================] - 0s 9ms/sample - loss: 362232.3224 - mean_squared_error: 362232.3125
Epoch 2/10
38/38 [==============================] - 0s 814us/sample - loss: 362229.5049 - mean_squared_error: 362229.5000
Epoch 3/10
38/38 [==============================] - 0s 341us/sample - loss: 362226.5477 - mean_squared_error: 362226.5625
Epoch 4/10
38/38 [==============================] - 0s 421us/sample - loss: 362223.4211 - mean_squared_error: 362223.4062
Epoch 5/10
38/38 [==============================] - 0s 394us/sample - loss: 362220.2368 - mean_squared_error: 362220.2500
Epoch 6/10
38/38 [==============================] - 0s 525us/sample - loss: 362216.9211 - mean_squared_error: 362216.9062
Epoch 7/10
38/38 [==============================] - 0s 264us/sample - loss: 362213.6332 - mean_squared_error: 362213.6250
Epoch 8/10
38/38 [==============================] - 0s 289us/sample - loss: 362210.0905 - mean_squared_error: 362210.0938
Epoch 9/10
38/38 [========

In [15]:
ypred=cat.predict(x_test)

In [16]:
ypred

array([[0.02869313],
       [0.03035789],
       [0.0267967 ],
       [0.02735857],
       [0.02726944],
       [0.02725884],
       [0.0269999 ],
       [0.02904072],
       [0.0273449 ],
       [0.02953987]], dtype=float32)

In [17]:
y_test

array([498, 524, 464, 628, 554, 344, 414, 587, 561, 635], dtype=int64)

In [18]:
cat.predict(sc.transform([[9.00,3571,1976,0.525]]))

array([[0.02753573]], dtype=float32)

In [21]:
cat.predict_classes(sc.transform([[9.00,3571,1976,0.525]]))

array([[0]])

In [22]:
cat.predict(sc.transform([[7.00,3897,6385,0.586]]))

array([[0.02828243]], dtype=float32)

In [23]:
cat.predict_classes(sc.transform([[7.00,3897,6385,0.586]]))

array([[0]])