In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Fish.csv")

In [3]:
dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
dataset["Species"].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
x=dataset.iloc[:,1:7].values
y=dataset.iloc[:,0:1].values

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [8]:
y.shape

(159, 7)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
cat=Sequential()

In [13]:
cat.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [16]:
cat.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

In [14]:
cat.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [17]:
cat.add(Dense(7,kernel_initializer="random_uniform",activation="softmax"))

In [18]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [19]:
cat.fit(x_train,y_train,batch_size=32,epochs=700)

Epoch 1/700
127/127 [==============================] - 2s 17ms/sample - loss: 1.9444 - acc: 0.3701
Epoch 2/700
127/127 [==============================] - 0s 126us/sample - loss: 1.9419 - acc: 0.3701
Epoch 3/700
127/127 [==============================] - 0s 189us/sample - loss: 1.9394 - acc: 0.3701
Epoch 4/700
127/127 [==============================] - 0s 126us/sample - loss: 1.9369 - acc: 0.3701
Epoch 5/700
127/127 [==============================] - 0s 189us/sample - loss: 1.9346 - acc: 0.3701
Epoch 6/700
127/127 [==============================] - 0s 189us/sample - loss: 1.9320 - acc: 0.3701
Epoch 7/700
127/127 [==============================] - 0s 189us/sample - loss: 1.9294 - acc: 0.3701
Epoch 8/700
127/127 [==============================] - 0s 189us/sample - loss: 1.9268 - acc: 0.3701
Epoch 9/700
127/127 [==============================] - 0s 315us/sample - loss: 1.9242 - acc: 0.3701
Epoch 10/700
127/127 [==============================] - 0s 189us/sample - loss: 1.9216 - acc: 0.3701


127/127 [==============================] - 0s 63us/sample - loss: 1.5439 - acc: 0.4646
Epoch 163/700
127/127 [==============================] - 0s 126us/sample - loss: 1.5386 - acc: 0.4646
Epoch 164/700
127/127 [==============================] - 0s 126us/sample - loss: 1.5332 - acc: 0.4646
Epoch 165/700
127/127 [==============================] - 0s 126us/sample - loss: 1.5277 - acc: 0.4646
Epoch 166/700
127/127 [==============================] - 0s 98us/sample - loss: 1.5232 - acc: 0.4646
Epoch 167/700
127/127 [==============================] - 0s 102us/sample - loss: 1.5188 - acc: 0.4646
Epoch 168/700
127/127 [==============================] - 0s 50us/sample - loss: 1.5136 - acc: 0.4646
Epoch 169/700
127/127 [==============================] - 0s 47us/sample - loss: 1.5098 - acc: 0.4646
Epoch 170/700
127/127 [==============================] - 0s 59us/sample - loss: 1.5045 - acc: 0.4646
Epoch 171/700
127/127 [==============================] - 0s 200us/sample - loss: 1.5007 - acc: 0.4646

127/127 [==============================] - 0s 63us/sample - loss: 1.2411 - acc: 0.4646
Epoch 323/700
127/127 [==============================] - 0s 63us/sample - loss: 1.2391 - acc: 0.4646
Epoch 324/700
127/127 [==============================] - 0s 126us/sample - loss: 1.2367 - acc: 0.4646
Epoch 325/700
127/127 [==============================] - 0s 126us/sample - loss: 1.2348 - acc: 0.4646
Epoch 326/700
127/127 [==============================] - 0s 63us/sample - loss: 1.2329 - acc: 0.4724
Epoch 327/700
127/127 [==============================] - 0s 126us/sample - loss: 1.2308 - acc: 0.4646
Epoch 328/700
127/127 [==============================] - 0s 189us/sample - loss: 1.2289 - acc: 0.4803
Epoch 329/700
127/127 [==============================] - 0s 126us/sample - loss: 1.2266 - acc: 0.4803
Epoch 330/700
127/127 [==============================] - 0s 126us/sample - loss: 1.2253 - acc: 0.4803
Epoch 331/700
127/127 [==============================] - 0s 63us/sample - loss: 1.2226 - acc: 0.480

127/127 [==============================] - 0s 126us/sample - loss: 1.0584 - acc: 0.5512
Epoch 483/700
127/127 [==============================] - 0s 126us/sample - loss: 1.0577 - acc: 0.5512
Epoch 484/700
127/127 [==============================] - 0s 63us/sample - loss: 1.0568 - acc: 0.5512
Epoch 485/700
127/127 [==============================] - 0s 126us/sample - loss: 1.0572 - acc: 0.5512
Epoch 486/700
127/127 [==============================] - 0s 189us/sample - loss: 1.0555 - acc: 0.5512
Epoch 487/700
127/127 [==============================] - 0s 126us/sample - loss: 1.0548 - acc: 0.5433
Epoch 488/700
127/127 [==============================] - 0s 126us/sample - loss: 1.0536 - acc: 0.5512
Epoch 489/700
127/127 [==============================] - 0s 189us/sample - loss: 1.0530 - acc: 0.5512
Epoch 490/700
127/127 [==============================] - 0s 126us/sample - loss: 1.0518 - acc: 0.5512
Epoch 491/700
127/127 [==============================] - 0s 63us/sample - loss: 1.0514 - acc: 0.5

127/127 [==============================] - 0s 126us/sample - loss: 0.8934 - acc: 0.7087
Epoch 643/700
127/127 [==============================] - 0s 63us/sample - loss: 0.8933 - acc: 0.7008
Epoch 644/700
127/127 [==============================] - 0s 126us/sample - loss: 0.8914 - acc: 0.7008
Epoch 645/700
127/127 [==============================] - 0s 126us/sample - loss: 0.8900 - acc: 0.7008
Epoch 646/700
127/127 [==============================] - 0s 63us/sample - loss: 0.8881 - acc: 0.7087
Epoch 647/700
127/127 [==============================] - 0s 126us/sample - loss: 0.8862 - acc: 0.7087
Epoch 648/700
127/127 [==============================] - 0s 126us/sample - loss: 0.8851 - acc: 0.7087
Epoch 649/700
127/127 [==============================] - 0s 126us/sample - loss: 0.8836 - acc: 0.7008
Epoch 650/700
127/127 [==============================] - 0s 126us/sample - loss: 0.8819 - acc: 0.6850
Epoch 651/700
127/127 [==============================] - ETA: 0s - loss: 0.8895 - acc: 0.687 - 0s 

In [20]:
x_train.shape

(127, 6)

In [21]:
y_train.shape

(127, 7)

In [22]:
ypred=cat.predict(x_test)

In [23]:
ypred

array([[5.65854132e-01, 5.63403766e-04, 3.76540571e-01, 1.68911708e-06,
        3.93014029e-02, 2.07051099e-03, 1.56682488e-02],
       [1.85330864e-02, 6.88780621e-02, 4.86638606e-01, 2.18719896e-03,
        2.49050468e-01, 1.51394665e-01, 2.33179107e-02],
       [6.74686357e-02, 2.28575207e-02, 6.23460054e-01, 3.51365976e-04,
        1.99139014e-01, 5.88592589e-02, 2.78641172e-02],
       [3.32361460e-02, 4.41486910e-02, 5.58482170e-01, 1.02318649e-03,
        2.33256608e-01, 1.03944935e-01, 2.59081926e-02],
       [6.19543672e-01, 3.90182511e-04, 3.32818359e-01, 1.04000389e-06,
        3.18921283e-02, 1.47094589e-03, 1.38836708e-02],
       [6.21865034e-01, 3.83710256e-04, 3.30910027e-01, 1.01728563e-06,
        3.15875225e-02, 1.44823093e-03, 1.38044432e-02],
       [6.30602479e-01, 3.60548001e-04, 3.23689014e-01, 9.37883954e-07,
        3.04659698e-02, 1.36641483e-03, 1.35147357e-02],
       [4.63566824e-10, 4.86944579e-02, 9.71296595e-06, 9.24709976e-01,
        1.87301717e-04, 2

In [24]:
ypred[0]

array([5.6585413e-01, 5.6340377e-04, 3.7654057e-01, 1.6891171e-06,
       3.9301403e-02, 2.0705110e-03, 1.5668249e-02], dtype=float32)

In [25]:
y_test[0] 

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=object)

In [26]:
cat.predict(sc.transform([[700,34,36,38.3,10.6091,6.7408]]))

array([[6.2046689e-01, 3.8757623e-04, 3.3206066e-01, 1.0308005e-06,
        3.1770233e-02, 1.4618153e-03, 1.3851754e-02]], dtype=float32)

In [27]:
cat.predict_classes(sc.transform([[700,34,36,38.3,10.6091,6.7408]]))

array([0], dtype=int64)