In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("bank.csv")

In [3]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
x=dataset.iloc[:,0:16].values
y=dataset.iloc[:,16:17].values

In [6]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder="passthrough")
x=ct.fit_transform(x)

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

C:\Users\bolla\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
x.shape

(11162, 51)

In [9]:
y.shape

(11162,)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [30]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [32]:
cat=Sequential()

In [33]:
cat.add(Dense(51,kernel_initializer="random_uniform",activation="relu"))

In [34]:
cat.add(Dense(102,kernel_initializer="random_uniform",activation="relu"))

In [35]:
cat.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [36]:
cat.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [38]:
cat.fit(x_train,y_train,batch_size=50,epochs=50)

Epoch 1/50
8929/8929 [==============================] - 1s 65us/sample - loss: 0.2398 - acc: 0.8986
Epoch 2/50
8929/8929 [==============================] - 1s 58us/sample - loss: 0.2350 - acc: 0.9016
Epoch 3/50
8929/8929 [==============================] - 1s 77us/sample - loss: 0.2371 - acc: 0.9003
Epoch 4/50
8929/8929 [==============================] - 1s 70us/sample - loss: 0.2318 - acc: 0.9004
Epoch 5/50
8929/8929 [==============================] - 1s 63us/sample - loss: 0.2301 - acc: 0.9028
Epoch 6/50
8929/8929 [==============================] - 1s 66us/sample - loss: 0.2248 - acc: 0.9042
Epoch 7/50
8929/8929 [==============================] - 1s 62us/sample - loss: 0.2210 - acc: 0.9081
Epoch 8/50
8929/8929 [==============================] - 1s 64us/sample - loss: 0.2192 - acc: 0.9084
Epoch 9/50
8929/8929 [==============================] - 1s 63us/sample - loss: 0.2177 - acc: 0.9098
Epoch 10/50
8929/8929 [==============================] - 1s 64us/sample - loss: 0.2156 - acc: 0.9084

In [39]:
y_train.shape

(8929,)

In [40]:
ypred=cat.predict(x_test)

In [41]:
ypred

array([[0.31713057],
       [0.        ],
       [0.0020653 ],
       ...,
       [0.99950993],
       [0.9973104 ],
       [0.99678206]], dtype=float32)

In [42]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [46]:
cat.predict(sc.transform(ct.transform([[43,"admin.","married","secondary","no",2300,"yes","no","unknown",4,"may",100,1,-1,0,"unknown"]])))

array([[2.4379892e-06]], dtype=float32)

In [47]:
cat.predict_classes(sc.transform(ct.transform([[43,"admin.","married","secondary","no",2300,"yes","no","unknown",4,"may",100,1,-1,0,"unknown"]])))

array([[0]])