In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("diabetes.csv")

In [3]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            8      183             64              0        0  23.3   
2            0      137             40             35      168  43.1   
3            3       78             50             32       88  31.0   
4            2      197             70             45      543  30.5   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos  
1                     0.672   32      pos  
2                     2.288   33      pos  
3                     0.248   26      pos  
4                     0.158   53      pos

In [4]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [5]:
x=dataset.iloc[:,0:8].values
y=dataset.iloc[:,8:9].values

In [6]:
y

array([['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       [

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

C:\Users\bolla\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
y.shape

(549,)

In [9]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1000)

In [51]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [52]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [53]:
cat=Sequential()

In [54]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

In [55]:
cat.add(Dense(16,kernel_initializer="random_uniform",activation="relu"))

In [56]:
cat.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [57]:
cat.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [58]:
cat.fit(x_train,y_train,batch_size=35,epochs=50)

Epoch 1/50
439/439 [==============================] - 0s 923us/sample - loss: 0.6930 - acc: 0.5308
Epoch 2/50
439/439 [==============================] - 0s 80us/sample - loss: 0.6924 - acc: 0.5376
Epoch 3/50
439/439 [==============================] - 0s 73us/sample - loss: 0.6910 - acc: 0.5854
Epoch 4/50
439/439 [==============================] - 0s 109us/sample - loss: 0.6879 - acc: 0.6674
Epoch 5/50
439/439 [==============================] - 0s 91us/sample - loss: 0.6824 - acc: 0.7153
Epoch 6/50
439/439 [==============================] - 0s 73us/sample - loss: 0.6731 - acc: 0.7175
Epoch 7/50
439/439 [==============================] - 0s 91us/sample - loss: 0.6590 - acc: 0.7198
Epoch 8/50
439/439 [==============================] - 0s 73us/sample - loss: 0.6401 - acc: 0.7312
Epoch 9/50
439/439 [==============================] - 0s 109us/sample - loss: 0.6172 - acc: 0.7426
Epoch 10/50
439/439 [==============================] - 0s 73us/sample - loss: 0.5930 - acc: 0.7472
Epoch 11/50
439/

In [59]:
ypred=cat.predict(x_test)

In [60]:
ypred

array([[0.18329689],
       [0.85989213],
       [0.05366752],
       [0.1258786 ],
       [0.02797595],
       [0.8086448 ],
       [0.73091424],
       [0.02964932],
       [0.8942306 ],
       [0.89065945],
       [0.06596512],
       [0.06316152],
       [0.32879087],
       [0.2687202 ],
       [0.39037377],
       [0.04217148],
       [0.8592721 ],
       [0.43509668],
       [0.33903033],
       [0.5023295 ],
       [0.15281424],
       [0.94002557],
       [0.09175789],
       [0.3012042 ],
       [0.91954863],
       [0.18180898],
       [0.46302825],
       [0.9242989 ],
       [0.10946241],
       [0.1637826 ],
       [0.14816934],
       [0.15228581],
       [0.64615947],
       [0.5880177 ],
       [0.8434167 ],
       [0.07758629],
       [0.59964216],
       [0.55432105],
       [0.6964333 ],
       [0.9368626 ],
       [0.35308695],
       [0.76646435],
       [0.11924478],
       [0.65136254],
       [0.9030106 ],
       [0.89835596],
       [0.16338515],
       [0.407

In [61]:
dataset.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos

In [62]:
cat.predict(sc.transform([[5,150,70,20,0,45.0,0.5,40]]))

array([[0.8721322]], dtype=float32)

In [64]:
cat.predict_classes(sc.transform([[5,150,70,20,0,45.0,0.5,40]]))

array([[1]])